// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/protobuf/empty.proto
// Protobuf Java Version: 4.28.2

package com.google.protobuf;

public final class EmptyProto {
  private EmptyProto() {}

  static {
    RuntimeVersion.validateProtobufGencodeVersion(
        RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 28,
        /* patch= */ 2,
        /* suffix= */ "",
        EmptyProto.class.getName());
  }

  public static void registerAllExtensions(ExtensionRegistryLite registry) {}

  public static void registerAllExtensions(ExtensionRegistry registry) {
    registerAllExtensions((ExtensionRegistryLite) registry);
  }

  static final Descriptors.Descriptor internal_static_google_protobuf_Empty_descriptor;
  static final GeneratedMessage.FieldAccessorTable
      internal_static_google_protobuf_Empty_fieldAccessorTable;

  public static Descriptors.FileDescriptor getDescriptor() {
    return descriptor;
  }

  private static Descriptors.FileDescriptor descriptor;

  static {
    String[] descriptorData = {
      "\n\033google/protobuf/empty.proto\022\017google.pr"
          + "otobuf\"\007\n\005EmptyB}\n\023com.google.protobufB\n"
          + "EmptyProtoP\001Z.google.golang.org/protobuf"
          + "/types/known/emptypb\370\001\001\242\002\003GPB\252\002\036Google.P"
          + "rotobuf.WellKnownTypesb\006proto3"
    };
    descriptor =
        Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(
            descriptorData, new Descriptors.FileDescriptor[] {});
    internal_static_google_protobuf_Empty_descriptor = getDescriptor().getMessageTypes().get(0);
    internal_static_google_protobuf_Empty_fieldAccessorTable =
        new GeneratedMessage.FieldAccessorTable(
            internal_static_google_protobuf_Empty_descriptor, new String[] {});
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
