// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/protobuf/timestamp.proto
// Protobuf Java Version: 4.28.2

package com.google.protobuf;

public final class TimestampProto {
  private TimestampProto() {}

  static {
    RuntimeVersion.validateProtobufGencodeVersion(
        RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 28,
        /* patch= */ 2,
        /* suffix= */ "",
        TimestampProto.class.getName());
  }

  public static void registerAllExtensions(ExtensionRegistryLite registry) {}

  public static void registerAllExtensions(ExtensionRegistry registry) {
    registerAllExtensions((ExtensionRegistryLite) registry);
  }

  static final Descriptors.Descriptor internal_static_google_protobuf_Timestamp_descriptor;
  static final GeneratedMessage.FieldAccessorTable
      internal_static_google_protobuf_Timestamp_fieldAccessorTable;

  public static Descriptors.FileDescriptor getDescriptor() {
    return descriptor;
  }

  private static Descriptors.FileDescriptor descriptor;

  static {
    String[] descriptorData = {
      "\n\037google/protobuf/timestamp.proto\022\017googl"
          + "e.protobuf\";\n\tTimestamp\022\030\n\007seconds\030\001 \001(\003"
          + "R\007seconds\022\024\n\005nanos\030\002 \001(\005R\005nanosB\205\001\n\023com."
          + "google.protobufB\016TimestampProtoP\001Z2googl"
          + "e.golang.org/protobuf/types/known/timest"
          + "amppb\370\001\001\242\002\003GPB\252\002\036Google.Protobuf.WellKno"
          + "wnTypesb\006proto3"
    };
    descriptor =
        Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(
            descriptorData, new Descriptors.FileDescriptor[] {});
    internal_static_google_protobuf_Timestamp_descriptor = getDescriptor().getMessageTypes().get(0);
    internal_static_google_protobuf_Timestamp_fieldAccessorTable =
        new GeneratedMessage.FieldAccessorTable(
            internal_static_google_protobuf_Timestamp_descriptor,
            new String[] {
              "Seconds", "Nanos",
            });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
